version: "3.9"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - poc_multi_tenancy
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  poc_multi_tenancy:
    driver: bridge

volumes:
  postgresql:
  postgresql_data:
